name: Test Coverage

on:
  push:
    branches: ["master"]

jobs:
  test_coverage:
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_code_quality.txt
      - name: Test
        run: |
          coverage run main_test.py
          coverage report
          coverage html
